container:
  image: cirrusci/flutter:3.0.5

task:
  build_script:
    - flutter pub get
    - flutter pub run build_runner build
    - flutter config --enable-web
    - flutter build web --profile
    - sed -i 's/main.dart.js/main.dart.js?version='"CIRRUS_BASE_SHA"'/' build/web/index.html
# curl -sL https://firebase.tools | bash
# printf '%s\n' "$SERVICE_FB" > /harness/test.json
# export GOOGLE_APPLICATION_CREDENTIALS="/harness/test.json"
# firebase use $PROJECT_ID
# firebase deploy --only hosting --debug
