include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'lib/services/arweave/graphql/**'
    - '**.g.dart'
    - 'build/**'
    - 'node_modules/**'
    - 'macos/**'
    - 'ios/**'
    - 'android/**'
    - 'web/**'
    - 'scripts/**'
    - 'docs/**'
    - 'drift_schemas/**'
    - 'packages/ario_sdk/lib/src/models/**'
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
linter:
  rules:
    prefer_single_quotes: true
