targets:
  $default:
    sources:
      - lib/**
      - pubspec.*
      - $package$
        # Allows the code generator to target files outside of the lib folder
      - integration_test/**.dart
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/services/arweave/graphql/graphql_api.dart
              schema: lib/services/arweave/graphql/schema.graphql
              queries_glob: lib/services/arweave/graphql/queries/**.graphql
          fragments_glob: lib/services/arweave/graphql/fragments/**.graphql
      drift_dev:
        options:
          named_parameters: true
