targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/services/arweave/graphql/graphql_api.dart
              schema: lib/services/arweave/graphql/schema.graphql
              queries_glob: lib/services/arweave/graphql/queries/**.graphql
          fragments_glob: lib/services/arweave/graphql/fragments/**.graphql
      moor_generator:
        options:
          named_parameters: true
