// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDXp0ZnEQfkUl4wEcfRVVR_EOwehrTFYrU',
//     appId: '1:305132849030:web:b2d30975b28774f8ffce07',
//     messagingSenderId: '305132849030',
//     projectId: 'ardrive-web',
//     authDomain: 'ardrive-web.firebaseapp.com',
//     databaseURL: 'https://ardrive-web.firebaseio.com',
//     storageBucket: 'ardrive-web.appspot.com',
//     measurementId: 'G-P05MMD1NHD',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA87mVW7WvBginbuihMcTNONWEMbqJBGvo',
//     appId: '1:305132849030:android:6cf0cd5ec064fad3ffce07',
//     messagingSenderId: '305132849030',
//     projectId: 'ardrive-web',
//     databaseURL: 'https://ardrive-web.firebaseio.com',
//     storageBucket: 'ardrive-web.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAVBeyv1xtODuezIcHol0ndj9hafOOLTpI',
//     appId: '1:305132849030:ios:06ea33a95a2e0d42ffce07',
//     messagingSenderId: '305132849030',
//     projectId: 'ardrive-web',
//     databaseURL: 'https://ardrive-web.firebaseio.com',
//     storageBucket: 'ardrive-web.appspot.com',
//     iosClientId:
//         '305132849030-ivpp5546vltkebnd06gui3ntj0fvavk6.apps.googleusercontent.com',
//     iosBundleId: 'io.ardrive.app',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAQ9bOkVPC5b6zlTE1i4Ei9xZ75abNXelc',
//     appId: '1:305132849030:ios:868d013a3867d8a5ffce07',
//     messagingSenderId: '305132849030',
//     projectId: 'ardrive-web',
//     databaseURL: 'https://ardrive-web.firebaseio.com',
//     storageBucket: 'ardrive-web.appspot.com',
//     iosClientId:
//         '305132849030-0opn0r5k7oa3bcilmvrnqocb97328gln.apps.googleusercontent.com',
//     iosBundleId: 'com.example.drive',
//   );
// }
