enum PlausiblePageView {
  fileExplorerPage, // FIXME: deprecate the other fileExplorer ones
  fileExplorerLoggedInUser,
  fileExplorerNewUserEmpty,
  fileExplorerNonLoggedInUser,
  tutorialsPage1,
  tutorialsPage2,
  tutorialsPage3,
  tutorialSkipped,
  createAndConfirmPasswordPage,
  createdAndConfirmedPassword,
  gettingStartedPage,
  enterSeedPhrasePage,
  logout,
  onboardingPage,
  sharedFilePage,
  turboPaymentDetails,
  turboPurchaseReview,
  turboTopUpModal,
  turboTopUpCancel,
  turboTopUpSuccess,
  verifySeedPhrasePage,
  writeDownSeedPhrasePage,
  walletDownloadPage,
  walletDownloaded,
  walletGenerationPage,
  welcomePage,
  welcomeBackPage,

  unknown,
}
