import 'package:ardrive/models/database/database.dart';
import 'package:drift_dev/api/migrations.dart';
import 'package:test/test.dart';

import '../../generated_migrations/schema.dart';

// The generated directory from before.

void main() {
  late SchemaVerifier verifier;

  setUpAll(() {
    // GeneratedHelper() was generated by drift, the verifier is an api
    // provided by drift_dev.
    verifier = SchemaVerifier(GeneratedHelper());
  });

  test('upgrade from v17 to v18', () async {
    // Use startAt(1) to obtain a database connection with all tables
    // from the v1 schema.
    final connection = await verifier.startAt(17);
    final db = Database(connection);

    // Use this to run a migration to v2 and then validate that the
    // database has the expected schema.
    await verifier.migrateAndValidate(db, 18);
  });

  // test('upgrade from v18 to v19', () async {
  //   // Use startAt(1) to obtain a database connection with all tables
  //   // from the v1 schema.
  //   final connection = await verifier.startAt(18);
  //   final db = Database(connection);

  //   // Use this to run a migration to v2 and then validate that the
  //   // database has the expected schema.
  //   await verifier.migrateAndValidate(db, 19);
  // });
}
