name: "Test and branch deploy storybook"

on:
  pull_request:
    branches-ignore:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  storybook:
    needs: test
    uses: ./.github/workflows/storybook.yml
    secrets: inherit
    with:
      FIREBASE_TARGET: "ardrive-ui"
      FIREBASE_EXPIRES: "14d"
