name: "Storybook staging deploy"

on:
  push:
    branches:
      - dev

jobs:
  test:
    uses: ./.github/workflows/test.yml

  storybook:
    needs: test
    uses: ./.github/workflows/storybook.yml
    secrets: inherit
    with:
      FIREBASE_TARGET: "ardrive-ui-staging"
      FIREBASE_CHANNEL: "live"
