on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v2

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}

      - name: Fetch dependencies
        run: flutter pub get

      - name: Fetch storybook dependencies
        working-directory: ./storybook
        run: flutter pub get

      - name: Lint
        run: flutter analyze

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v2

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          cache: true

      - name: Fetch dependencies
        run: flutter pub get

      - name: Fetch storybook dependencies
        working-directory: ./storybook
        run: flutter pub get

      - name: Test
        run: flutter test
