name: ardrive_ui
description: UI Design Library for the ArDrive Design System

version: 1.18.0

publish_to: "none"

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: 3.13.6

dependencies:
  ardrive_io:
    git:
      url: https://github.com/ardriveapp/ardrive_io.git
      ref: v1.4.3
  auto_size_text: ^3.0.0
  desktop_drop: ^0.4.0
  dotted_border: ^2.0.0+3
  flutter:
    sdk: flutter
  flutter_portal: ^1.1.2
  flutter_svg: ^1.1.6
  percent_indicator: ^4.2.2
  flutter_svg_image: 1.0.0
  provider: ^6.0.5
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/icons/
  fonts:
    - family: ArDriveIcons
      fonts:
        - asset: assets/fonts/ArDriveIcons.ttf
    - family: Wavehaus
      fonts:
        - asset: assets/fonts/Wavehaus-28Thin.otf
          weight: 300
        - asset: assets/fonts/Wavehaus-42Light.otf
          weight: 400
        - asset: assets/fonts/Wavehaus-66Book.otf
          weight: 500
        - asset: assets/fonts/Wavehaus-95SemiBold.otf
          weight: 600
        - asset: assets/fonts/Wavehaus-128Bold.otf
          weight: 700
        - asset: assets/fonts/Wavehaus-158ExtraBold.otf
          weight: 800
