name: file_saver
description: >-
  This package will help you save file with a single method on any platform
  including macOS, iOS, Android, Windows, Web, Linux.
version: 0.1.1

repository: https://github.com/incrediblezayed/file_saver

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  path_provider: ^2.0.9
  path_provider_windows: ^2.0.5
  path_provider_linux: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.one.file_saver
        pluginClass: FileSaverPlugin
      ios:
        pluginClass: FileSaverPlugin
      linux:
        pluginClass: FileSaverPlugin
      macos:
        pluginClass: FileSaverPlugin
      windows:
        pluginClass: FileSaverPlugin
      web:
        pluginClass: FileSaverWeb
        fileName: file_saver_web.dart
