name: deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  # Use this if you want the tests to run in a different job and not interfere with the deploy
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         persist-credentials: false
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         flutter-version: '2.2.x'
  #     - name: Prepare app
  #       run: |
  #         flutter pub get
  #         flutter pub run build_runner build
  #     - name: Run tests
  #       run: flutter test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.x'
      - name: Build app
        run: |
          flutter pub get
          flutter pub run build_runner build
          flutter test
          flutter config --enable-web
          flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_CI_SERVICE_ACCOUNT }}'
          channelId: live
